/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ProdukController;
import model.Produk;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author taqim
 */
public class ProdukForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProdukForm.class.getName());

    /**
     * Creates new form ProdukForm
     */
    public ProdukForm() {
        initComponents();
        loadTable();
    }

    private void loadTable() {

        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("ID Perabot");
        model.addColumn("Nama");
        model.addColumn("Jenis");
        model.addColumn("Status");
        model.addColumn("Stok");
        model.addColumn("Harga");
        model.addColumn("Zona");
        model.addColumn("Nomor Rak");
        model.addColumn("Posisi Rak");

        ProdukController controller = new ProdukController();
        List<Produk> daftarProduk = controller.tampilSemua();

        for (Produk p : daftarProduk) {

            model.addRow(new Object[]{
                p.getIdPerabot(),
                p.getNamaPerabot(),
                p.getJenisPerabot(),
                p.getStatusPerabot(),
                p.getStok(),
                p.getHarga(),
                p.getZona(),
                p.getNomorRak(),
                p.getPosisiRak()
            });

        }

        tblProduk.setModel(model);

    }
    private void clearForm() {

    txtIdPerabot.setText("");
    txtNamaPerabot.setText("");
    txtJenisPerabot.setText("");
    txtStatusPerabot.setText("");
    txtStok.setText("");
    txtHarga.setText("");
    txtZona.setText("");
    txtNomorRak.setText("");
    txtPosisiRak.setText("");

    txtIdPerabot.requestFocus();

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        lblJudul = new javax.swing.JLabel();
        lblIdPerabot = new javax.swing.JLabel();
        lblNamaPerabot = new javax.swing.JLabel();
        lblJenisPerabot = new javax.swing.JLabel();
        lblStatusPerabot = new javax.swing.JLabel();
        lblStok = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        lblZona = new javax.swing.JLabel();
        lblNomorRak = new javax.swing.JLabel();
        lblPosisiRak = new javax.swing.JLabel();
        txtIdPerabot = new javax.swing.JTextField();
        txtNamaPerabot = new javax.swing.JTextField();
        txtJenisPerabot = new javax.swing.JTextField();
        txtStatusPerabot = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtZona = new javax.swing.JTextField();
        txtNomorRak = new javax.swing.JTextField();
        txtPosisiRak = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduk = new javax.swing.JTable();

        jTextField4.addActionListener(this::jTextField4ActionPerformed);

        jTextField8.addActionListener(this::jTextField8ActionPerformed);

        jButton4.setText("jButton1");

        jButton7.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJudul.setText("DATA PRODUK ");
        lblJudul.setToolTipText("");

        lblIdPerabot.setText("ID Perabot          :");

        lblNamaPerabot.setText("Nama Perabot    :");

        lblJenisPerabot.setText("Jenis Perabot      :");

        lblStatusPerabot.setText("Status Perabot    :");

        lblStok.setText("Stok                     :");

        lblHarga.setText("Harga                  :");

        lblZona.setText("Zona                    :");

        lblNomorRak.setText("Nomor Rak          :");

        lblPosisiRak.setText("Posisi Rak             :");

        txtIdPerabot.addActionListener(this::txtIdPerabotActionPerformed);

        txtNamaPerabot.addActionListener(this::txtNamaPerabotActionPerformed);

        txtJenisPerabot.addActionListener(this::txtJenisPerabotActionPerformed);

        txtStatusPerabot.addActionListener(this::txtStatusPerabotActionPerformed);

        txtStok.addActionListener(this::txtStokActionPerformed);

        txtHarga.addActionListener(this::txtHargaActionPerformed);

        txtZona.addActionListener(this::txtZonaActionPerformed);

        txtNomorRak.addActionListener(this::txtNomorRakActionPerformed);

        txtPosisiRak.addActionListener(this::txtPosisiRakActionPerformed);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(this::btnUbahActionPerformed);

        btnHapus.setText("Hapus");

        btnCari.setText("Cari");

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnKembali.setText("Kembali");

        tblProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduk);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblIdPerabot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNamaPerabot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblJenisPerabot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStatusPerabot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblZona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNomorRak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPosisiRak, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdPerabot, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamaPerabot, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJenisPerabot, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStatusPerabot, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtZona, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomorRak, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPosisiRak, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnSimpan)
                            .addGap(47, 47, 47)
                            .addComponent(btnUbah)
                            .addGap(55, 55, 55)
                            .addComponent(btnHapus)
                            .addGap(42, 42, 42)
                            .addComponent(btnCari)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReset)
                            .addGap(66, 66, 66)
                            .addComponent(btnKembali))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblJudul)
                .addGap(307, 307, 307))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdPerabot)
                    .addComponent(txtIdPerabot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamaPerabot)
                    .addComponent(txtNamaPerabot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJenisPerabot)
                    .addComponent(txtJenisPerabot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatusPerabot)
                    .addComponent(txtStatusPerabot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStok)
                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHarga)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblZona)
                    .addComponent(txtZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomorRak, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomorRak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPosisiRak)
                    .addComponent(txtPosisiRak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCari)
                    .addComponent(btnHapus)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSimpan)
                        .addComponent(btnReset)
                        .addComponent(btnKembali)
                        .addComponent(btnUbah)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdPerabotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPerabotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPerabotActionPerformed

    private void txtNamaPerabotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPerabotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPerabotActionPerformed

    private void txtJenisPerabotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisPerabotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisPerabotActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void txtStatusPerabotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusPerabotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusPerabotActionPerformed

    private void txtStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStokActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void txtZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZonaActionPerformed

    private void txtNomorRakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomorRakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomorRakActionPerformed

    private void txtPosisiRakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPosisiRakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPosisiRakActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {

            Produk produk = new Produk();

            produk.setIdPerabot(txtIdPerabot.getText());
            produk.setNamaPerabot(txtNamaPerabot.getText());
            produk.setJenisPerabot(txtJenisPerabot.getText());
            produk.setStatusPerabot(txtStatusPerabot.getText());
            produk.setStok(Integer.parseInt(txtStok.getText()));
            produk.setHarga(Double.parseDouble(txtHarga.getText()));
            produk.setZona(txtZona.getText());
            produk.setNomorRak(txtNomorRak.getText());
            produk.setPosisiRak(txtPosisiRak.getText());

            ProdukController controller = new ProdukController();
            controller.tambah(produk);

            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
            clearForm();
            loadTable();
        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this,
                    "Stok dan Harga harus berupa angka!");
        }

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        try {

        Produk produk = new Produk();

        produk.setIdPerabot(txtIdPerabot.getText());
        produk.setNamaPerabot(txtNamaPerabot.getText());
        produk.setJenisPerabot(txtJenisPerabot.getText());
        produk.setStatusPerabot(txtStatusPerabot.getText());
        produk.setStok(Integer.parseInt(txtStok.getText()));
        produk.setHarga(Double.parseDouble(txtHarga.getText()));
        produk.setZona(txtZona.getText());
        produk.setNomorRak(txtNomorRak.getText());
        produk.setPosisiRak(txtPosisiRak.getText());

        ProdukController controller = new ProdukController();
        controller.ubah(produk);

        JOptionPane.showMessageDialog(this, "Data berhasil diubah!");

        clearForm();
        loadTable();

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(this,
                "Stok dan Harga harus berupa angka!");

    }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        clearForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdukMouseClicked
        int baris = tblProduk.getSelectedRow();

    txtIdPerabot.setText(tblProduk.getValueAt(baris, 0).toString());
    txtNamaPerabot.setText(tblProduk.getValueAt(baris, 1).toString());
    txtJenisPerabot.setText(tblProduk.getValueAt(baris, 2).toString());
    txtStatusPerabot.setText(tblProduk.getValueAt(baris, 3).toString());
    txtStok.setText(tblProduk.getValueAt(baris, 4).toString());
    txtHarga.setText(tblProduk.getValueAt(baris, 5).toString());
    txtZona.setText(tblProduk.getValueAt(baris, 6).toString());
    txtNomorRak.setText(tblProduk.getValueAt(baris, 7).toString());
    txtPosisiRak.setText(tblProduk.getValueAt(baris, 8).toString());
    }//GEN-LAST:event_tblProdukMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProdukForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblIdPerabot;
    private javax.swing.JLabel lblJenisPerabot;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblNamaPerabot;
    private javax.swing.JLabel lblNomorRak;
    private javax.swing.JLabel lblPosisiRak;
    private javax.swing.JLabel lblStatusPerabot;
    private javax.swing.JLabel lblStok;
    private javax.swing.JLabel lblZona;
    private javax.swing.JTable tblProduk;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIdPerabot;
    private javax.swing.JTextField txtJenisPerabot;
    private javax.swing.JTextField txtNamaPerabot;
    private javax.swing.JTextField txtNomorRak;
    private javax.swing.JTextField txtPosisiRak;
    private javax.swing.JTextField txtStatusPerabot;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtZona;
    // End of variables declaration//GEN-END:variables
}
